# Generated by Django 3.2.7 on 2021-09-15 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_medicalappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappointment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='usuário que marcou'),
            preserve_default=False,
        ),
    ]
