# Generated by Django 3.2.7 on 2021-09-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletime',
            options={'verbose_name': 'Horário', 'verbose_name_plural': 'Hórarios'},
        ),
        migrations.AlterField(
            model_name='scheduletime',
            name='time',
            field=models.TimeField(unique=True, verbose_name='horário'),
        ),
    ]
