# Generated by Django 3.2.7 on 2021-09-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210915_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='has_available_time',
            field=models.BooleanField(default=True, verbose_name='tem horário livre'),
        ),
    ]
